"""Add course structure and user progress

Revision ID: 4025410fb644
Revises: 793e996f1f2d
Create Date: 2025-06-26 04:24:52.084042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4025410fb644'
down_revision: Union[str, None] = '793e996f1f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('module_id', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('order_index', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('lesson_type', sa.String(length=50), nullable=True))
    op.add_column('lessons', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'modules', ['module_id'], ['id'])
    op.drop_column('lessons', 'category')
    op.drop_column('lessons', 'difficulty_level')
    op.add_column('quiz_questions', sa.Column('question_type', sa.String(length=50), nullable=True))
    op.add_column('quiz_responses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_responses', 'users', ['user_id'], ['id'])
    op.add_column('quizzes', sa.Column('lesson_id', sa.Integer(), nullable=False))
    op.add_column('quizzes', sa.Column('passing_score', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quizzes', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'time_limit')
    op.drop_column('quizzes', 'passing_score')
    op.drop_column('quizzes', 'lesson_id')
    op.drop_constraint(None, 'quiz_responses', type_='foreignkey')
    op.drop_column('quiz_responses', 'user_id')
    op.drop_column('quiz_questions', 'question_type')
    op.add_column('lessons', sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'estimated_duration')
    op.drop_column('lessons', 'media_url')
    op.drop_column('lessons', 'lesson_type')
    op.drop_column('lessons', 'order_index')
    op.drop_column('lessons', 'module_id')
    # ### end Alembic commands ###
